[package]
name = "updatethis"
version = "0.1.2"
edition = "2024"
description = "A tiny CLI to programmatically update the version of an R package"
repository = "https://github.com/JosiahParry/updatethis"
license = "MIT"
publish = false

# `publish = false` otherwise hides this binary from cargo-dist.
[package.metadata.dist]
dist = true

[dependencies]
anyhow = "1"
clap = { version = "=4.6.1", features = ["derive"] }
colored = "3.1.1"
r-description = { git = "https://github.com/JosiahParry/r-description-rs", branch = "fix/setters" }

[profile.release]
codegen-units = 1
lto = true

[profile.dist]
inherits = "release"
